### ISSUE TITLE
Migrate from bower to npm

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/agent-mockup#4]

**Comment by srang** [comment]
Not sure if these have to be mutually exclusive. I mean it depends on what you're trying to do but I'm pretty sure there are ways to set up gulp to install both bower and npm as separate tasks. It would be more consolidated if we got them all in one tool but we could also use it as a separation of concerns where bower is used for application dependencies and styling (bootstrap, jquery, fontawesome), and then in our package.json we have build and development dependencies (gulp plugins etc). Just a thought

**Comment by mondalaci** [comment]
@srang We could use both bower and npm indeed, but it'd be redundant because unlike bower, npm contains pretty much every library imaginable, both server-side and client-side. That's the reason why it'd be worth to migrate exclusively to npm.

**Comment by srang** [comment]
I'm on board with that. Just thought I'd play devils advocate.

**Comment by mondalaci** [comment]
@csanyiarpad Let's not add any files of `node_modules` to `master`. We should however add the dependent files to `gh-pages`, upon the next deploy.
